package com.sangmeebee.weatherlist.model

const val SEOUL_ZIP = "04524,KR"
const val CHICAGO_ZIP = "60007,US"
const val LONDON_ZIP = "E14,GB"

const val DAY_CLEAR_SKY = "01d"
const val DAY_FEW_CLOUDS = "02d"
const val DAY_SCATTERED_CLOUDS = "03d"
const val DAY_BROKEN_CLOUDS = "04d"
const val DAY_SHOWER_RAIN = "09d"
const val DAY_RAIN = "10d"
const val DAY_THUNDER_STORM = "11d"
const val DAY_SNOW = "13d"
const val DAY_MIST = "50d"

const val NIGHT_CLEAR_SKY = "01n"
const val NIGHT_FEW_CLOUDS = "02n"
const val NIGHT_SCATTERED_CLOUDS = "03n"
const val NIGHT_BROKEN_CLOUDS = "04n"
const val NIGHT_SHOWER_RAIN = "09n"
const val NIGHT_RAIN = "10n"
const val NIGHT_THUNDER_STORM = "11n"
const val NIGHT_SNOW = "13n"
const val NIGHT_MIST = "50n"
